# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-15T00:08:33+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class Status(Enum):
    available = 'available'
    pending = 'pending'
    sold = 'sold'


class Pet(BaseModel):
    id: int
    name: str
    tag: Optional[str] = None
    status: Optional[Status] = None


class NewPet(BaseModel):
    name: str
    tag: Optional[str] = None
    status: Optional[Status] = None
