# generated by datamodel-codegen:
#   filename:  sample_schema.json
#   timestamp: 2026-05-14T23:53:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, EmailStr, Field, conint


class Address(BaseModel):
    street: str
    city: str
    zip_code: Optional[str] = None


class User(BaseModel):
    id: int = Field(..., description='Unique identifier for the user')
    name: str = Field(..., description='Full name of the user')
    email: EmailStr = Field(..., description='Email address')
    age: Optional[conint(ge=0, le=150)] = None
    address: Optional[Address] = None
    tags: Optional[List[str]] = None
